# Stage 1: Chef
FROM rust:1.96 AS chef

RUN cargo install cargo-chef cargo-watch

WORKDIR /app

# Stage 2: Planner
FROM chef AS planner

COPY . .
RUN cargo chef prepare --recipe-path recipe.json

# Stage 3: Builder
FROM chef AS builder

COPY --from=planner /app/recipe.json recipe.json

RUN cargo chef cook --recipe-path recipe.json

COPY . .

EXPOSE 8080

CMD ["cargo", "watch", "-x", "run"]
